@startuml storeManager_Vendeur
left to right direction
skinparam packageStyle rectangle

actor "Chargé de Vente" as V

rectangle "StoreManager Pro -  Vendeur" {

    usecase "Se connecter" as U

    usecase "voir dashboard vendeur (POS)" as POS
    usecase "Rechercher un produit / code-barres" as RP
    usecase "Ajouter un produit au ligne" as AP
    usecase "Modifier la quantité du ligne" as MQ
    usecase "Sélectionner un client" as SC
    usecase "Vérifier la limite de crédit client" as VLC
    usecase "Choisir le mode de règlement (Espèces, Wave, OM, Dette)" as MR
    usecase "Valider la vente" as EV
    usecase "Annuler la ligne" as ANN

    usecase "Accéder à l'écran Dettes Clients" as GD
    usecase "Consulter la liste des dettes clients" as LD
    usecase "Enregistrer un règlement de dette" as EPD
}


V --> POS
V --> GD

POS --> RP : <<include>>
POS --> AP : <<include>>
POS --> MQ : <<extend>>
POS --> SC : <<include>>
SC ..> VLC : <<include>>
POS --> MR : <<include>>
POS --> EV : <<include>>
POS --> ANN : <<extend>>

U <.. RP : <<include>>
U <.. AP : <<include>>
U <.. MQ : <<include>>
U <.. SC : <<include>>
U <.. VLC : <<include>>
U <.. MR : <<include>>
U <.. EV : <<include>>
U <.. ANN : <<extend>>

GD --> LD : <<include>>
GD ..> EPD : <<extend>>


@enduml
