@startuml storeManager_Global
left to right direction
skinparam packageStyle rectangle

actor " Admin Boutique" as Admin
actor " Chargé de Vente" as Vendeur
actor " Chargé de Stock" as Stock
actor " Inventaire" as Inventaire

rectangle "StoreManager Pro - ERP Application" {

    
    usecase "Se connecter" as Login

    
    usecase "Tableau de bord (Dashboard)" as DASH
    usecase "Caisse tactile (POS)" as POS
    usecase "Suivi des Dettes Clients" as DETTES
    usecase "Approvisionnements (BLs)" as SUPPLIES
    usecase "Catalogue & Tiers (Produits, Clients, Fournisseurs)" as CATALOG

   
    usecase "Consulter les KPIs & alertes" as KPIs
    usecase "Effectuer une vente" as Vente
    usecase "Enregistrer un paiement dette" as PaiementDette
    usecase "Réceptionner un Bon de Livraison" as ReceptionBL
    usecase "Gérer produits, clients et fournisseurs" as GestionCatalogue
}

Admin --> DASH
Admin --> POS
Admin --> DETTES
Admin --> SUPPLIES
Admin --> CATALOG

Vendeur --> POS
Vendeur --> DETTES

Stock --> SUPPLIES
Stock --> CATALOG

Inventaire --> CATALOG


DASH --> KPIs : <<include>>
POS --> Vente : <<include>>
DETTES --> PaiementDette : <<include>>
SUPPLIES --> ReceptionBL : <<include>>
CATALOG --> GestionCatalogue : <<include>>


DASH ..> Login : <<include>>
POS ..> Login : <<include>>
DETTES ..> Login : <<include>>
SUPPLIES ..> Login : <<include>>
CATALOG ..> Login : <<include>>

@enduml
