@startuml storeManager_Inventaire
left to right direction
skinparam packageStyle rectangle

actor "Inventaire" as I

rectangle "StoreManager Pro -  Inventaire" {

    usecase "Se connecter" as U

  
    usecase "voir statistique(Tiers & Produits)" as VS

    usecase "gerer les produits" as GP
    usecase "saisir un produit au catalogue" as AP
    usecase "lister et filtrer les produits en stock" as LP
    usecase "enregistrer produit" as EP

    usecase "gerer les fournisseurs" as GF
     usecase "Consulter le répertoire des fournisseurs" as LF
    usecase "saisir un fournisseur" as AF
    usecase "enregistrer fournisseur" as EF


    usecase "gerer les clients" as GC
    usecase "lister le répertoire des clients" as LC
    usecase "saisir un client" as AC
    usecase "enregistrer client" as EC

    
   
}

I --> VS
VS ..> : <<include>>
I --> GF
I --> GP
I --> GC

GF ..> LF : <<include>>
GF ..> AF : <<include>>
AF <.. EF : <<extend>>

GP ..> LP: <<include>>
GP ..> AP: <<include>>
AP <.. EP: <<extend>>

GC ..> LC: <<include>>
GC ..> AC: <<include>>
AC <.. EC: <<extend>>

 EF ..> U: <<include>>
 EC ..> U: <<include>>
 EP ..> U: <<include>>





@enduml
