@startuml storeManager_Stock
left to right direction
skinparam packageStyle rectangle

actor "Chargé de Stock" as S

rectangle "StoreManager Pro -  Stock" {

    usecase "Se connecter" as UC_Login

    usecase "Accéder à dashboard Approvisionnements" as GAPP
    usecase "Créer un Bon de Livraison (BL)" as NBL
    usecase "Sélectionner un fournisseur" as SF
    usecase "Ajouter des articles au BL" as ABL
    usecase "Valider et enregistrer la réception du BL" as EVBL
    usecase "Consulter l'historique des réceptions" as LBL

    usecase "Accéder à dashboard Catalogue (Produits & Fournisseurs)" as GCAT
    usecase "Consulter les produits et alertes stock bas" as LP
    usecase "Ajouter un nouveau produit" as AP
    usecase "Ajouter un fournisseur" as AF
    usecase "Consulter la liste des fournisseurs" as LF
}

S --> UC_Login
S --> GAPP
S --> GCAT


GAPP --> NBL : <<include>>
GAPP --> LBL : <<include>>
NBL --> SF : <<include>>
NBL --> ABL : <<include>>
NBL --> EVBL : <<include>>


GCAT --> LP : <<include>>
GCAT --> AP : <<extend>>
GCAT --> AF : <<extend>>
GCAT --> LF : <<include>>

' Accès sécurisé
GAPP ..> UC_Login : <<include>>
GCAT ..> UC_Login : <<include>>

@enduml
