@startuml storeManager_Vendeur
left to right direction
skinparam packageStyle rectangle

actor "Chargé de Vente" as V

rectangle "StoreManager Pro - Application Vendeur" {

    ' Authentification
    usecase "Se connecter" as UC_Login

    ' Vue 1 : Écran Caisse Tactile / POS
    usecase "Accéder à l'écran Caisse (POS)" as POS
    usecase "Rechercher un produit / code-barres" as RP
    usecase "Ajouter un produit au panier" as AP
    usecase "Modifier la quantité du panier" as MQ
    usecase "Sélectionner un client" as SC
    usecase "Vérifier la limite de crédit client" as VLC
    usecase "Choisir le mode de règlement (Espèces, Wave, OM, Dette)" as MR
    usecase "Valider la vente" as EV
    usecase "Annuler le panier" as ANN

    ' Vue 2 : Écran Suivi des Dettes
    usecase "Accéder à l'écran Dettes Clients" as GD
    usecase "Consulter la liste des dettes clients" as LD
    usecase "Enregistrer un règlement de dette" as EPD
}

' Interactions Acteur -> Écrans autorisés
V --> UC_Login
V --> POS
V --> GD

' Écran POS -> Actions
POS --> RP : <<include>>
POS --> AP : <<include>>
POS --> MQ : <<extend>>
POS --> SC : <<include>>
SC ..> VLC : <<include>>
POS --> MR : <<include>>
POS --> EV : <<include>>
POS --> ANN : <<extend>>

' Écran Dettes -> Actions
GD --> LD : <<include>>
GD --> EPD : <<include>>

' Accès sécurisé
POS ..> UC_Login : <<include>>
GD ..> UC_Login : <<include>>

@enduml
